import { TrendCard, Client } from "./types"

export const MOCK_CLIENTS: Client[] = [
  { id: "1", name: "MercadoLibre", category: "ecommerce", slackChannelId: null, market: "ARG", active: true },
  { id: "2", name: "Danone", category: "food_bev", slackChannelId: null, market: "ARG", active: true },
  { id: "3", name: "Disney", category: "entretenimiento", slackChannelId: null, market: "ARG", active: true },
  { id: "4", name: "Rappi", category: "delivery", slackChannelId: null, market: "ARG", active: true },
  { id: "5", name: "Despegar", category: "travel", slackChannelId: null, market: "ARG", active: true },
  { id: "6", name: "PedidosYa", category: "delivery", slackChannelId: null, market: "ARG", active: true },
  { id: "7", name: "CCU", category: "food_bev", slackChannelId: null, market: "ARG", active: true },
  { id: "8", name: "NaranjaX", category: "fintech", slackChannelId: null, market: "ARG", active: true },
]

export const MOCK_TRENDS: TrendCard[] = [
  {
    id: "t1",
    name: "POV: cuando te llega el paquete",
    platform: "tiktok",
    score: 9.2,
    growthSpeed: 9.5,
    activationWindow: "URGENTE",
    categoryFit: 9.0,
    description: "Formato de unboxing emocional donde el creator recibe un paquete y su reaccion es el contenido. El hook es la anticipacion — no se sabe que hay adentro. Exploto en TikTok ARG en las ultimas 48hs con marcas de ecommerce adaptandolo.",
    manifestation: "Video corto (15-30s), POV en primera persona, camara selfie, reaccion genuina al abrir el paquete. Audio trending: sonido de timbre + musica de suspenso que cambia a celebracion.",
    examples: "Videos con 500K+ views en TikTok ARG usando el formato con productos de tecnologia y moda.",
    whyNow: "El formato conecta con la cultura de compra online post-Hot Sale. La gente esta recibiendo paquetes y el formato canaliza esa emocion de manera viral.",
    recommendedFormat: "UGC",
    status: "NEW",
    market: "ARG",
    clients: [
      { id: "1", name: "MercadoLibre", category: "ecommerce" },
      { id: "4", name: "Rappi", category: "delivery" },
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "t2",
    name: "Aesthetic de almuerzo casero",
    platform: "instagram",
    score: 7.8,
    growthSpeed: 7.0,
    activationWindow: "NORMAL",
    categoryFit: 8.5,
    description: "Contenido aspiracional pero alcanzable de almuerzos caseros con estetica cuidada. No es cocina gourmet — es el plato de todos los dias filmado con buena luz y composicion. Crece en Reels ARG con el hashtag #AlmuerzoDeCasa.",
    manifestation: "Reel de 15-20s, cenital o 45 grados, luz natural, plato terminado con detalle de textura. Sin receta — solo el resultado. Audio: musica lofi o ambiente.",
    examples: "Hashtag #AlmuerzoDeCasa con 12M views en la ultima semana en Instagram ARG.",
    whyNow: "Otono en Argentina, la gente vuelve a cocinar en casa. El formato es simple de producir y tiene alto engagement porque genera identificacion.",
    recommendedFormat: "ESTATICA",
    status: "NEW",
    market: "ARG",
    clients: [
      { id: "2", name: "Danone", category: "food_bev" },
      { id: "7", name: "CCU", category: "food_bev" },
    ],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "t3",
    name: "Nostalgia 2000s: volvio el low-rise",
    platform: "pinterest",
    score: 7.2,
    growthSpeed: 6.5,
    activationWindow: "NORMAL",
    categoryFit: 7.0,
    description: "Busquedas de estetica Y2K y low-rise jeans creciendo 340% en Pinterest ARG. La nostalgia de los 2000s esta volviendo con fuerza en moda, accesorios y estetica general.",
    manifestation: "Pins de outfits Y2K, moodboards con estetica 2000s, referencias a Paris Hilton, butterfly clips, velour tracksuits. Busquedas crecientes: 'outfit 2000', 'y2k aesthetic argentina'.",
    examples: "Busqueda 'Y2K outfit' crecio 340% en los ultimos 30 dias en Pinterest ARG.",
    whyNow: "La Gen Z esta descubriendo la estetica de los 2000s y la esta reinterpretando. Es ciclico pero el pico en ARG esta siendo ahora.",
    recommendedFormat: "ESTATICA",
    status: "EVALUATING",
    market: "ARG",
    clients: [
      { id: "3", name: "Disney", category: "entretenimiento" },
    ],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "t4",
    name: "Memes de inflacion argenta",
    platform: "reddit",
    score: 6.5,
    growthSpeed: 8.0,
    activationWindow: "URGENTE",
    categoryFit: 5.5,
    description: "Nueva ola de memes sobre inflacion y precios en r/argentina. El formato es comparacion 'expectativa vs realidad' del supermercado. Tono: humor negro tipico argento.",
    manifestation: "Memes de imagen con formato antes/despues de ir al super. Templates de 'crying jordan' y 'this is fine' adaptados al contexto argentino.",
    examples: "Posts en r/argentina con 2K+ upvotes en las ultimas 24hs sobre precios del supermercado.",
    whyNow: "Nuevos aumentos de precios generan una ola de humor como mecanismo de coping. Las marcas que se suben con autocritica ganan engagement.",
    recommendedFormat: "ESTATICA",
    status: "NEW",
    market: "ARG",
    clients: [
      { id: "4", name: "Rappi", category: "delivery" },
      { id: "6", name: "PedidosYa", category: "delivery" },
    ],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "t5",
    name: "Challenge: 'Sin filtro en 5 segundos'",
    platform: "tiktok",
    score: 8.7,
    growthSpeed: 9.0,
    activationWindow: "URGENTE",
    categoryFit: 8.0,
    description: "Challenge donde el creator muestra algo 'real' en 5 segundos sin filtro, edicion ni preparacion. Puede ser su cara, su casa, su comida, su trabajo. La autenticidad es el hook.",
    manifestation: "Video de 10-15s, cuenta regresiva en pantalla, transicion brusca a lo 'real'. Audio trending: sonido de alarma + 'show me in 5 seconds'. Formatos: cara sin maquillaje, heladera real, escritorio real.",
    examples: "El hashtag #SinFiltro5Seg tiene 45M views en TikTok LATAM esta semana.",
    whyNow: "Reaccion a la saturacion de contenido ultra-producido. La audiencia premia la autenticidad y este formato la fuerza de manera divertida.",
    recommendedFormat: "UGC",
    status: "NEW",
    market: "ARG",
    clients: [
      { id: "1", name: "MercadoLibre", category: "ecommerce" },
      { id: "8", name: "NaranjaX", category: "fintech" },
      { id: "5", name: "Despegar", category: "travel" },
    ],
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "t6",
    name: "Busqueda: 'escapadas fin de semana cerca de BA'",
    platform: "google_trends",
    score: 7.5,
    growthSpeed: 7.8,
    activationWindow: "NORMAL",
    categoryFit: 9.0,
    description: "Pico de busquedas de escapadas de fin de semana desde Buenos Aires. Las busquedas incluyen 'escapada barata', 'fin de semana cerca de buenos aires', 'donde ir este finde'.",
    manifestation: "Busquedas en Google creciendo 200% vs semana anterior. Concentradas en viernes y sabado. Relacionadas con destinos como Tigre, San Antonio de Areco, Colonia.",
    examples: "Google Trends muestra pico de busqueda de 'escapada fin de semana' en las ultimas 48hs.",
    whyNow: "Feriado largo se acerca. La gente busca opciones accesibles para salir de la ciudad sin gastar mucho.",
    recommendedFormat: "AD",
    status: "ACTIVATED",
    market: "ARG",
    clients: [
      { id: "5", name: "Despegar", category: "travel" },
    ],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
]
